apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-azure-config
  namespace: kube-system
  labels:
    app: fluent-bit
data:
  # Replace these values with your Azure Monitor configuration
  # Data Collection Endpoint URL
  dce-url: "https://dce-for-fluent-bit-3fw9.centralus-1.ingest.monitor.azure.com"
  # Data Collection Rule immutable ID
  dcr-id: "dcr-db234b9ff2624bae94be4ceba71737e9"
  # Custom table name in Log Analytics workspace
  table-name: "MyFluentBitLogs"
