apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-azure-blob-config
  namespace: kube-system
  labels:
    app: fluent-bit
data:
  # Azure Storage Account name for blob storage
  storage-account: "01h10sgithublogs"
